-- 新規環境向けの area_count_records 最終スキーマです。
-- 既存環境では、このファイルではなく次の順で実行してください。
-- 1. supabase_area_count_records_backup.sql
-- 2. supabase_area_count_records_migration.sql
-- 3. supabase_area_count_records_verify.sql
-- 問題がある場合だけ supabase_area_count_records_rollback.sql を実行します。

create table if not exists public.area_count_records (
  id bigint generated by default as identity primary key,
  data_schema_version integer check (data_schema_version >= 1),
  app_version text,
  build_id text,
  date text not null,
  session_started_at text not null,
  recorded_at timestamptz not null,
  area_id text not null,
  discount_time text not null check (discount_time in ('15', '17', '18', '19', '20')),
  actual_weekday text check (actual_weekday in ('日', '月', '火', '水', '木', '金', '土')),
  actual_weekday_group text not null check (
    actual_weekday_group in (
      '月水', '火木', '金土日', '火木日', '金土', '三連休中日', '翌日平日祝日'
    )
  ),
  count integer not null check (count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (date, session_started_at, area_id, discount_time)
);

create index if not exists area_count_records_lookup_idx
  on public.area_count_records (area_id, discount_time, actual_weekday, recorded_at desc);

create index if not exists area_count_records_group_lookup_idx
  on public.area_count_records (area_id, discount_time, actual_weekday_group, recorded_at desc);

create or replace function public.set_area_count_records_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_area_count_records_updated_at on public.area_count_records;
create trigger set_area_count_records_updated_at
before update on public.area_count_records
for each row
execute function public.set_area_count_records_updated_at();

alter table public.area_count_records enable row level security;

-- 認証なしで全員が同じ売場データを共有する前提の最小ポリシーです。
-- deleteは許可しません。
drop policy if exists "area_count_records_select" on public.area_count_records;
create policy "area_count_records_select"
on public.area_count_records
for select
to anon
using (true);

drop policy if exists "area_count_records_insert" on public.area_count_records;
create policy "area_count_records_insert"
on public.area_count_records
for insert
to anon
with check (true);

drop policy if exists "area_count_records_update" on public.area_count_records;
create policy "area_count_records_update"
on public.area_count_records
for update
to anon
using (true)
with check (true);
