-- Supabase SQL editorで実行するSQLです。
-- エリア残数履歴だけをサーバー保存するためのテーブルを作成します。

create table if not exists public.area_count_records (
  id bigint generated by default as identity primary key,
  data_schema_version integer check (data_schema_version >= 1),
  app_version text,
  date text not null,
  session_started_at text not null,
  recorded_at timestamptz not null,
  area_id text not null,
  discount_time text not null check (discount_time in ('15', '17', '18', '19', '20')),
  weekday_base text check (weekday_base in ('日', '金土', '火木', '月水')),
  actual_weekday text check (actual_weekday in ('日', '月', '火', '水', '木', '金', '土')),
  actual_weekday_group text not null check (actual_weekday_group in ('月水', '火木', '金土日', '火木日', '金土', '三連休中日', '翌日平日祝日')),
  count integer not null check (count >= 0),
  user_judge text check (user_judge in ('many', 'slightly_many', 'normal', 'slightly_few', 'few')),
  suggested_evaluation text check (suggested_evaluation in ('many', 'slightly_many', 'normal', 'slightly_few', 'few')),
  area_rate_adjustment integer check (area_rate_adjustment in (-10, -5, 0, 5, 10)),
  evaluation_source text check (evaluation_source in ('manual', 'history')),
  decision_basis jsonb,
  comfort_point integer check (comfort_point between -1 and 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (date, session_started_at, area_id, discount_time)
);

-- 既存テーブルを使っている場合も、このSQLを再実行すれば新しい判定根拠列を追加できます。
alter table public.area_count_records
  add column if not exists data_schema_version integer check (data_schema_version >= 1);

alter table public.area_count_records
  add column if not exists app_version text;

alter table public.area_count_records
  add column if not exists evaluation_source text check (evaluation_source in ('manual', 'history'));

alter table public.area_count_records
  add column if not exists decision_basis jsonb;

-- 時刻別・三連休中日・翌日平日祝日の新グループ名を保存できるよう、既存列の許可値だけを拡張します。
-- 旧グループ名は読み込み時の互換変換に必要なため、引き続き許可します。
alter table public.area_count_records
  drop constraint if exists area_count_records_actual_weekday_group_check;

alter table public.area_count_records
  add constraint area_count_records_actual_weekday_group_check
  check (actual_weekday_group in ('月水', '火木', '金土日', '火木日', '金土', '三連休中日', '翌日平日祝日'));

-- 旧版はuser_judgeを3段階に制限していたため、現在の5段階入力を保存できるよう更新します。
alter table public.area_count_records
  drop constraint if exists area_count_records_user_judge_check;

alter table public.area_count_records
  add constraint area_count_records_user_judge_check
  check (user_judge in ('many', 'slightly_many', 'normal', 'slightly_few', 'few'));

create index if not exists area_count_records_lookup_idx
  on public.area_count_records (area_id, discount_time, actual_weekday, recorded_at desc);

create index if not exists area_count_records_group_lookup_idx
  on public.area_count_records (area_id, discount_time, actual_weekday_group, recorded_at desc);

create or replace function public.set_area_count_records_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_area_count_records_updated_at on public.area_count_records;
create trigger set_area_count_records_updated_at
before update on public.area_count_records
for each row
execute function public.set_area_count_records_updated_at();

alter table public.area_count_records enable row level security;

-- 認証なしで全員が同じ売場データを共有する前提の最小ポリシーです。
-- deleteは許可していません。
drop policy if exists "area_count_records_select" on public.area_count_records;
create policy "area_count_records_select"
on public.area_count_records
for select
to anon
using (true);

drop policy if exists "area_count_records_insert" on public.area_count_records;
create policy "area_count_records_insert"
on public.area_count_records
for insert
to anon
with check (true);

drop policy if exists "area_count_records_update" on public.area_count_records;
create policy "area_count_records_update"
on public.area_count_records
for update
to anon
using (true)
with check (true);
